import { createServer } from "miragejs";

createServer({
  routes() {
    this.namespace = "api";

    this.get("/movies", () => {
      return {
        movies: [
          {
            id: 1,
            title: "Plain Basic T-Shirt",
            category: "tshirt",
            img: "/tshirt/tshirt-one/tshirt-one.webp",
            description: "",
            price: 998,
            extraImg: [
              "/tshirt/tshirt-one/tshirt-one-e-1.webp",
              "/tshirt/tshirt-one/tshirt-one-e-2.webp",
              "/tshirt/tshirt-one/tshirt-one-e-3.webp",
              "/tshirt/tshirt-one/tshirt-one-e-4.webp",
            ],
          },
          {
            id: 2,
            title: "Basic V-Neck T-Shirt",
            category: "tshirt",
            img: "/tshirt/tshirt-two/tshirt-two.webp",
            description: "",
            price: 998,
            extraImg: [
              "/tshirt/tshirt-two/tshirt-two-e-1.webp",
              "/tshirt/tshirt-two/tshirt-two-e-2.webp",
              "/tshirt/tshirt-two/tshirt-two-e-3.webp",
              "/tshirt/tshirt-two/tshirt-two-e-4.webp",
            ],
          },
          {
            id: 3,
            title: "Sports Jersey T-Shirt",
            category: "tshirt",
            img: "/tshirt/tshirt-three/tshirt-three.webp",
            description: "",
            price: 748,
            extraImg: [
              "/tshirt/tshirt-three/tshirt-three-e-1.webp",
              "/tshirt/tshirt-three/tshirt-three-e-2.webp",
              "/tshirt/tshirt-three/tshirt-three-e-3.webp",
              "/tshirt/tshirt-three/tshirt-three-e-4.webp",
            ],
          },
          {
            id: 4,
            title: "Lycra Basic T-Shirt",
            category: "tshirt",
            img: "/tshirt/tshirt-four/tshirt-four.webp",
            description: "",
            price: 1378,
            extraImg: [
              "/tshirt/tshirt-four/tshirt-four-e-1.webp",
              "/tshirt/tshirt-four/tshirt-four-e-2.webp",
              "/tshirt/tshirt-four/tshirt-four-e-3.webp",
              "/tshirt/tshirt-four/tshirt-four-e-4.webp",
            ],
          },
          {
            id: 5,
            title: "Full Sleeve Shirt",
            category: "shirt",
            img: "/shirt/shirt-one/shirt-one.webp",
            description: "",
            price: 1598,
            extraImg: [
              "/shirt/shirt-one/shirt-one-e-1.webp",
              "/shirt/shirt-one/shirt-one-e-2.webp",
              "/shirt/shirt-one/shirt-one-e-3.webp",
            ],
          },
          {
            id: 6,
            title: "Embroidered Button-Up Top",
            category: "shirt",
            img: "/shirt/shirt-two/shirt-two.webp",
            description: "",
            price: 1498,
            extraImg: [
              "/shirt/shirt-two/shirt-two-e-1.webp",
              "/shirt/shirt-two/shirt-two-e-2.webp",
              "/shirt/shirt-two/shirt-two-e-3.webp",
            ],
          },
          {
            id: 7,
            title: "Plain Half Shirt",
            category: "shirt",
            img: "/shirt/shirt-three/shirt-three.webp",
            description: "",
            price: 1998,
            extraImg: [
              "/shirt/shirt-three/shirt-three-e-1.webp",
              "/shirt/shirt-three/shirt-three-e-2.webp",
              "/shirt/shirt-three/shirt-three-e-3.webp",
              "/shirt/shirt-three/shirt-three-e-4.webp",
            ],
          },
          {
            id: 8,
            title: "Oxford Band Collar Shirt",
            category: "shirt",
            img: "/shirt/shirt-four/shirt-four.webp",
            description: "",
            price: 2078,
            extraImg: [
              "/shirt/shirt-four/shirt-four-e-1.webp",
              "/shirt/shirt-four/shirt-four-e-2.webp",
              "/shirt/shirt-four/shirt-four-e-3.webp",
              "/shirt/shirt-four/shirt-four-e-4.webp",
            ],
          },
          {
            id: 9,
            title: "Polar Fleece Zip High Neck",
            category: "sweatshirt",
            img: "/sweatshirt/sweatshirt-one/sweatshirt-one.webp",
            description: "",
            price: 1998,
            extraImg: [
              "/sweatshirt/sweatshirt-one/sweatshirt-one-e-1.webp",
              "/sweatshirt/sweatshirt-one/sweatshirt-one-e-2.webp",
              "/sweatshirt/sweatshirt-one/sweatshirt-one-e-3.webp",
              "/sweatshirt/sweatshirt-one/sweatshirt-one-e-4.webp",
            ],
          },
          {
            id: 10,
            title: "Single Fleece High Neck",
            category: "sweatshirt",
            img: "/sweatshirt/sweatshirt-two/sweatshirt-two.webp",
            description: "",
            price: 1078,
            extraImg: [
              "/sweatshirt/sweatshirt-two/sweatshirt-two-e-1.webp",
              "/sweatshirt/sweatshirt-two/sweatshirt-two-e-2.webp",
              "/sweatshirt/sweatshirt-two/sweatshirt-two-e-3.webp",
              "/sweatshirt/sweatshirt-two/sweatshirt-two-e-4.webp",
            ],
          },
          {
            id: 11,
            title: "Single Fleece Zip High Neck",
            category: "sweatshirt",
            img: "/sweatshirt/sweatshirt-three/sweatshirt-three.webp",
            description: "",
            price: 1798,
            extraImg: [
              "/sweatshirt/sweatshirt-three/sweatshirt-three-e-1.webp",
              "/sweatshirt/sweatshirt-three/sweatshirt-three-e-2.webp",
              "/sweatshirt/sweatshirt-three/sweatshirt-three-e-3.webp",
              "/sweatshirt/sweatshirt-three/sweatshirt-three-e-4.webp",
            ],
          },
          {
            id: 12,
            title: "Rib-Knit Hoodie",
            category: "sweatshirt",
            img: "/sweatshirt/sweatshirt-four/sweatshirt-four.webp",
            description: "",
            price: 2398,
            extraImg: [
              "/sweatshirt/sweatshirt-four/sweatshirt-four-e-1.webp",
              "/sweatshirt/sweatshirt-four/sweatshirt-four-e-2.webp",
              "/sweatshirt/sweatshirt-four/sweatshirt-four-e-3.webp",
            ],
          },
          {
            id: 13,
            title: "Ripstop Chino Shorts",
            category: "shorts",
            img: "/shorts/shorts-one/shorts-one.webp",
            description: "",
            price: 2198,
            extraImg: [
              "/shorts/shorts-one/shorts-one-e-1.webp",
              "/shorts/shorts-one/shorts-one-e-2.webp",
              "/shorts/shorts-one/shorts-one-e-3.webp",
              "/shorts/shorts-one/shorts-one-e-4.webp",
            ],
          },
          {
            id: 14,
            title: "Zip-Pocket Shorts",
            category: "shorts",
            img: "/shorts/shorts-two/shorts-two.webp",
            description: "",
            price: 1648,
            extraImg: [
              "/shorts/shorts-two/shorts-two-e-1.webp",
              "/shorts/shorts-two/shorts-two-e-2.webp",
              "/shorts/shorts-two/shorts-two-e-3.webp",
            ],
          },
          {
            id: 15,
            title: "Chino Shorts",
            category: "shorts",
            img: "/shorts/shorts-three/shorts-three.webp",
            description: "",
            price: 1798,
            extraImg: [
              "/shorts/shorts-three/shorts-three-e-1.webp",
              "/shorts/shorts-three/shorts-three-e-2.webp",
              "/shorts/shorts-three/shorts-three-e-3.webp",
              "/shorts/shorts-three/shorts-three-e-4.webp",
            ],
          },
          {
            id: 16,
            title: "Summer Shorts",
            category: "shorts",
            img: "/shorts/shorts-four/shorts-four.webp",
            description: "",
            price: 1398,
            extraImg: [
              "/shorts/shorts-four/shorts-four-e-1.webp",
              "/shorts/shorts-four/shorts-four-e-2.webp",
            ],
          },
          {
            id: 17,
            title: "Tencel Shorts",
            category: "shorts",
            img: "/shorts/shorts-five/shorts-five.webp",
            description: "",
            price: 1348,
            extraImg: [
              "/shorts/shorts-five/shorts-five-e-1.webp",
              "/shorts/shorts-five/shorts-five-e-2.webp",
              "/shorts/shorts-five/shorts-five-e-3.webp",
              "/shorts/shorts-five/shorts-five-e-4.webp",
            ],
          },
          {
            id: 18,
            title: "UFO Shorts",
            category: "shorts",
            img: "/shorts/shorts-four/shorts-four.webp",
            description: "",
            price: 1298,
            extraImg: [
              "/shorts/shorts-four/shorts-four-e-1.webp",
              "/shorts/shorts-four/shorts-four-e-2.webp",
              "/shorts/shorts-four/shorts-four-e-3.webp",
              "/shorts/shorts-four/shorts-four-e-4.webp",
            ],
          },
        ],
      };
    });
  },
});
